apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: <APP_NAME>
  namespace: <K8S_NAMESPACE>
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: <APP_NAME>
  targetCPUUtilizationPercentage: 70
