apiVersion: v1
kind: Service
metadata:
  name: <APP_NAME>
  namespace: <K8S_NAMESPACE>
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: NodePort
  selector:
    app: <APP_NAME>
