image: <DOCKER_IMAGE>

stages:
  - CodeQuality
  - Building
  - Deploy
  - SmokeTests
  - PromoteToProduction

include:
  - local: .gitlab-ci/code-quality.yml
  - local: .gitlab-ci/build.yml
  - local: .gitlab-ci/deploy.yml
  - local: .gitlab-ci/feature-tests.yml
  - local: .gitlab-ci/promote-to-production.yml
