version: "3"
services:
  app:
    extends:
      file: docker-compose.yml
      service: app

  redis:
    extends:
      file: docker-compose.yml
      service: redis

volumes:
  db_data:
    driver: "local"
  cache_data:
    driver: "local"

networks:
  app_network:
    driver: "bridge"