linting:
  stage: CodeQuality
  only:
    refs:
      - merge_requests
  tags:
    - <RUNNER_NAME>
  script: sh .gitlab-ci/scripts/linting.sh

unit-tests:
  stage: CodeQuality
  only:
    refs:
      - merge_requests
  tags:
    - <RUNNER_NAME>
  script: sh .gitlab-ci/scripts/unit-tests.sh

code-coverage:
  stage: CodeQuality
  only:
    refs:
      - merge_requests
  tags:
    - <RUNNER_NAME>
  script:
    - |
      readonly DESIRED_CODE_COVERAGE=80
      readonly CODE_COVERAGE=$(sh .gitlab-ci/scripts/code-coverage.sh | tr -dc '0-9')

      if [[ "${CODE_COVERAGE}" -lt "${DESIRED_CODE_COVERAGE}" ]]; then
        echo "Desired code coverage level is ${DESIRED_CODE_COVERAGE}% found ${CODE_COVERAGE}%"
        exit 1
      fi
